### ISSUE TITLE
有没有项目文档呀

### ISSUE THREAD

**Issue by 94659960** [We-sson/HanGao#1]
方便的话 QQ 94659960

**Comment by We-sson** [comment]
感谢关注！该项目处于半成品研发状态，详细项目文档正在编写后续会更新推送！


![企业微信截图_17210061561094](https://github.com/user-attachments/assets/d5099d93-a5c3-4d17-a229-453032ab5c80)

**Comment by 94659960** [comment]
我一直在写.net，对该项目非常有兴趣，可否一起参与一下呀。
________________________________

**Comment by We-sson** [comment]
**感谢各位开发者喜欢，该项目现有本人进行细分领域的工艺开发，属于非标软件。**
本项目可自下载参考和观摩，感谢各位对该项目非常有兴趣！
