### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by linshuchang** [We-sson/HanGao#2]
![PixPin_2024-12-20_10-52-55](https://github.com/user-attachments/assets/e0b24b09-c5be-436f-a196-f3c96552173d)
启动不了

**Comment by We-sson** [comment]
#2 项目首次启动使用Debug/Release模型启动项目需要加载大约一百多调试符号文件，首次启动时间长达3~30分钟（由电脑性能IO决定和网络速度），后续可使用Release模式启动，重复省去加载调试符号文件。

VS默认符号文件加载设置
![image](https://github.com/user-attachments/assets/bea9b206-737b-4a23-998a-6d9a2ccb0025)
